### PR TITLE
updated texture of the feeder module item

### PR DESCRIPTION
**Pull request by TimGoll**
closing #8

### CODE REVIEW

**Comment by canitzp** [comment]
Is there any particular reason for this change? I have nothing against it, but I would like to know why you have done this

**Comment by TimGoll** [comment]
I did not like the original one :D
Therefore I created a new one for myself but I thought you might want to use it

**Comment by canitzp** [comment]
a future plan is to add the module as overlay to a feeder helmet. can you make sure that, if this texture is the overlay of a helmet, that it looks good? The old one did, cause my artist thought that i would implement it earlier

**Comment by TimGoll** [comment]
uhm, yes. But not today. What about two different textures? One for the inventory and one as an overlay?

**Comment by canitzp** [comment]
two textures would be okay

**Pull request closed without merging**
